#!/usr/bin/env sh

# Load Husky
. "$(dirname -- "$0")/_/husky.sh"

# Run prettier on modified files
npm run pretty-quick

# Uncomment to format all files
# echo "Formatting all files with Prettier..."
# npx prettier --write .

# Run linting
nx affected:lint
